
filter:
    excluded_paths:
        - 'vendor/*'
        - 'Tests/*'
        - 'bin/*'

checks:
    php: true

coding_style:
    php:
        spaces:
            before_keywords:
                catch: false

tools:
    external_code_coverage: true
