# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 7

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer update --prefer-source --no-interaction


# Commands you want to run that will verify your build.
script: bin/phpunit -c . --coverage-clover=./build/coverage/coverage.clover

#after_script:
#  - php bin/coveralls -v

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/coverage/coverage.clover

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
#  allow_failures:
#    - php: 7
#    - php: hhvm
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always