language: php
sudo: false

env:
  global:
    - PATH="$HOME/bin:./vendor/bin:$PATH"

matrix:
  fast_finish: true
  include:
    - php: '7.2'
    - php: '7.2'
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: '7.2'
      env: SYMFONY=3.4.*
    - php: '7.2'
      env: SYMFONY=4.0.*
    - php: '7.3'
      env: SYMFONY=4.0.*
    - php: '7.4'
      env: SYMFONY=4.0.*
    - php: '7.2'
      env: SYMFONY=5.0.*
    - php: '7.3'
      env: SYMFONY=5.0.*
    - php: '7.4'
      env: SYMFONY=5.0.*
    - php: '7.4'
      env: SYMFONY=dev-master
  allow_failures:
    - php: '7.4'
    - env: SYMFONY=dev-master

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update
  - if [ "$GITHUB_OAUTH_TOKEN" != "" ]; then composer config --quiet --global github-oauth.github.com ${GITHUB_OAUTH_TOKEN}; fi;
  - if [ "$SYMFONY" != "" ]; then composer require "symfony/symfony:${SYMFONY}" --no-update; fi;
  - composer require "php-coveralls/php-coveralls" --no-update

install:
  - mkdir --parents "${HOME}/bin"
  - wget https://scrutinizer-ci.com/ocular.phar --output-document="${HOME}/bin/ocular" && chmod +x "${HOME}/bin/ocular"
  - composer global require --prefer-dist --no-interaction sllh/composer-lint:@stable
  - composer update --prefer-dist --no-interaction ${COMPOSER_FLAGS}
  - vendor/bin/simple-phpunit install

before_script:
  - echo "zend_extension=xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - composer validate
  - vendor/bin/simple-phpunit --coverage-clover=./build/coverage/coverage.xml

after_success:
  - ocular code-coverage:upload --format=php-clover ./build/coverage/coverage.xml
  - php vendor/bin/coveralls -v

notifications:
  on_success: never
  on_failure: always
