language: php

php:
  - '7.0'
  - nightly

matrix:
  fast_finish: true
  include:
    - php: '7.0'
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: '7.0'
      env: SYMFONY=2.8.*
    - php: '7.0'
      env: SYMFONY=3.0.*
    - php: '7.0'
      env: SYMFONY=3.1.*
    - php: '7.0'
      env: SYMFONY=dev-master
  allow_failures:
    - php: nightly
    - env: SYMFONY=3.1.*
    - env: SYMFONY=dev-master

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update
  - composer config --quiet --global github-oauth.github.com ${GITHUB_OAUTH_TOKEN}
  - if [ "$SYMFONY" != "" ]; then composer require "symfony/symfony:${SYMFONY}" --no-update; fi;

install:
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer update --prefer-dist --no-interaction ${COMPOSER_FLAGS}

script: bin/phpunit -c . --coverage-clover=./build/coverage/coverage.clover

after_success:
  - php ocular.phar code-coverage:upload --format=php-clover ./build/coverage/coverage.clover

notifications:
    on_success: never
    on_failure: always
